= Ethereum pet-shop tutorial (step by step, using Truffle)
Paulo Jerônimo <paulojeronimo@gmail.com>; {localdatetime}
:toc:
:icons: font
:Cygwin: http://www.cygwin.com/[Cygwin]

:step01-title: Creating a Truffle project using a Truffle Box
:step02-title: Writing the smart contract
:step02-1-title: Variable setup
:step02-2-title: Your first function: Adopting a pet
:step02-3-title: Your second function: Retrieving the adopters
:step03-title: Compiling and migrating the smart contract
:step04-title: Testing the smart contract
:step05-title: Creating a user interface to interact with the smart contract
:step06-title: Interacting with the dapp in a browser

:step01-url: http://truffleframework.com/tutorials/pet-shop#creating-a-truffle-project-using-a-truffle-box
:step02-url: http://truffleframework.com/tutorials/pet-shop#writing-the-smart-contract
:step02-1-url: http://truffleframework.com/tutorials/pet-shop#variable-setup
:step02-2-url: http://truffleframework.com/tutorials/pet-shop#your-first-function-adopting-a-pet
:step02-3-url: http://truffleframework.com/tutorials/pet-shop#your-second-function-retrieving-the-adopters
:step03-url: http://truffleframework.com/tutorials/pet-shop#compiling-and-migrating-the-smart-contract
:step04-url: http://truffleframework.com/tutorials/pet-shop#testing-the-smart-contract
:step05-url: http://truffleframework.com/tutorials/pet-shop#creating-a-user-interface-to-interact-with-the-smart-contract
:step06-url: http://truffleframework.com/tutorials/pet-shop#interacting-with-the-dapp-in-a-browser

:step01: {step01-url}[Introduction]
:step02: {step02-url}[Introduction]
:step02-1: {step02-1-url}[{step02-1-title}]
:step02-2: {step02-2-url}[{step02-2-title}]
:step02-3: {step02-3-url}[{step02-3-title}]
:step03: {step03-url}[Introduction]
:step04: {step04-url}[Introduction]
:step05: {step05-url}[Introduction]
:step06: {step06-url}[Introduction]

This is a way to execute the http://truffleframework.com/tutorials/pet-shop["Ethereum Pet Shop"] (https://github.com/trufflesuite/trufflesuite.com/blob/master/public/tutorials/pet-shop.md[source page] edited on Dec 22, 2017). You can follow the steps below only by copying and paste the commands (from here to your Bash shell). When you finish running the steps presented here, you will get a local git repository called `ethereum-pet-shop` (https://github.com/paulojeronimo/ethereum-pet-shop[like this]).

[NOTE]
====
. To continue you will need a Bash shell environment (of course) with Git installed.
. I only tested this steps on macOS and Linux. Maybe it can be run in Windows (through {Cygwin} for example).
====

[[step00]]
== Load some basic shell functions

Before start, install `node` and `npm`.

[TIP]
.Installation on Arch Linux
====
----
$ sudo pacman -S node npm
----
====

[NOTE]
.Last environment tested (on macOS)
====
----
$ node -v
v9.8.0
$ npm -v 
5.6.0
----
====

Load the link:functions[] in your current shell:

----
source ./functions
----

NOTE: This file contains some useful functions (`pet-shop*`) that I have created to minimize the number of commands that we need to type in this tutorial.

[[step01]]
== {step01-title}

{step01}

----
$ npm install -g truffle
----

WARNING: On Arch Linux run the command above with `sudo`.

----
$ truffle version
----

[NOTE]
.Last environment tested (on macOS)
====
----
$ truffle version
Truffle v4.1.3 (core: 4.1.3)
Solidity v0.4.19 (solc-js)
----
====

----
$ mkdir ethereum-pet-shop && cd $_
$ truffle unbox pet-shop
$ find . ! -path './node_modules/*'
$ pet-shop init
----

[[step02]]
== {step02-title}

{step02}

----
$ pet-shop add contracts/Adoption.sol <<'EOF'
pragma solidity ^0.4.17;

contract Adoption {

}
EOF
$ git log
----

{step02-1}

[subs="attributes+"]
----
$ pet-shop apply ../patches/01.patch '{step02-1-title}'
$ git log
----

{step02-2}

[subs="attributes+"]
----
$ pet-shop apply ../patches/02.patch '{step02-2-title}'
----

{step02-3}

[subs="attributes+"]
----
$ pet-shop apply ../patches/03.patch '{step02-3-title}'
----

[[step03]]
== {step03-title}

{step03}

----
$ truffle compile
# some warnings will appear ... normal!
----

----
$ pet-shop add migrations/2_deploy_contracts.js <<'EOF'
var Adoption = artifacts.require("Adoption");

module.exports = function(deployer) {
  deployer.deploy(Adoption);
};
EOF
----

Download and install http://truffleframework.com/ganache[Ganache]. Double click the icon to launch the application.

[TIP]
.Installation/ execution on Arch Linux
====
----
$ yaourt ganache
$ ganache &> /dev/null &
----
====

----
$ truffle migrate
$ tree build/
----

----
$ echo build >> .gitignore
$ git commit -am 'File .gitignore modified'
----

[[step04]]
== {step04-title}

{step04}

----
$ pet-shop add test/TestAdoption.sol <<'EOF'
pragma solidity ^0.4.17;

import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
import "../contracts/Adoption.sol";

contract TestAdoption {
  Adoption adoption = Adoption(DeployedAddresses.Adoption());

}
EOF
----

http://truffleframework.com/tutorials/pet-shop#testing-the-adopt-function[Testing the adopt() function]

----
$ pet-shop apply ../patches/04.patch 'Testing the adopt() function'
----

http://truffleframework.com/tutorials/pet-shop#testing-retrieval-of-a-single-pet-39-s-owner[Testing retrieval of a single pet's owner]

----
$ pet-shop apply ../patches/05.patch "Testing retrieval of a single pet's owner"
----

http://truffleframework.com/tutorials/pet-shop#testing-retrieval-of-all-pet-owners[Testing retrieval of all pet owners]

----
$ pet-shop apply ../patches/06.patch "Testing retrieval of all pet owners"
----

http://truffleframework.com/tutorials/pet-shop#running-the-tests[Running the tests]

----
$ truffle test
----

[[step05]]
== {step05-title}

{step05}

http://truffleframework.com/tutorials/pet-shop#instantiating-web3[Instantiating web3]

----
$ pet-shop apply ../patches/07.patch 'Instantiating web3'
----

http://truffleframework.com/tutorials/pet-shop#instantiating-the-contract[Instantiating the contract]

----
$ pet-shop apply ../patches/08.patch 'Instantiating the contract'
----

http://truffleframework.com/tutorials/pet-shop#getting-the-adopted-pets-and-updating-the-ui[Getting The Adopted Pets and Updating The UI]

----
$ pet-shop apply ../patches/09.patch 'Getting The Adopted Pets and Updating The UI'
----

http://truffleframework.com/tutorials/pet-shop#handling-the-adopt-function[Handling the adopt() Function]

----
$ pet-shop apply ../patches/10.patch 'Handling the adopt() Function'
----

[[step06]]
== {step06-title}

{step06}

http://truffleframework.com/tutorials/pet-shop#installing-and-configuring-metamask[Installing and configuring MetaMask]

http://truffleframework.com/tutorials/pet-shop#installing-and-configuring-lite-server[Installing and configuring lite-server]

----
$ cat bs-config.json
$ sed -n '9,12p' package.json
----

http://truffleframework.com/tutorials/pet-shop#using-the-dapp[Using the dapp]

----
$ npm run dev
----

Congratulations! You have taken a huge step to becoming a full-fledged dapp developer.
