= Ethereum pet-shop tutorial (step by step, using Truffle)
Paulo Jerônimo <paulojeronimo@gmail.com>; {localdatetime}
:toc:
:icons: font
:Cygwin: http://www.cygwin.com/[Cygwin]

:step00-title: Setting up the development environment
:step01-title: Creating a Truffle project using a Truffle Box
:step02-title: Writing the smart contract
:step02-1-title: Variable setup
:step02-2-title: Your first function: Adopting a pet
:step02-3-title: Your second function: Retrieving the adopters
:step03-title: Compiling and migrating the smart contract
:step04-title: Testing the smart contract
:step05-title: Creating a user interface to interact with the smart contract
:step06-title: Interacting with the dapp in a browser

:step01-url: https://www.trufflesuite.com/tutorials/pet-shop#creating-a-truffle-project-using-a-truffle-box
:step02-url: https://www.trufflesuite.com/tutorials/pet-shop#writing-the-smart-contract
:step02-1-url: https://www.trufflesuite.com/tutorials/pet-shop#variable-setup
:step02-2-url: https://www.trufflesuite.com/tutorials/pet-shop#your-first-function-adopting-a-pet
:step02-3-url: https://www.trufflesuite.com/tutorials/pet-shop#your-second-function-retrieving-the-adopters
:step03-url: https://www.trufflesuite.com/tutorials/pet-shop#compiling-and-migrating-the-smart-contract
:step04-url: https://www.trufflesuite.com/tutorials/pet-shop#testing-the-smart-contract
:step05-url: https://www.trufflesuite.com/tutorials/pet-shop#creating-a-user-interface-to-interact-with-the-smart-contract
:step06-url: https://www.trufflesuite.com/tutorials/pet-shop#interacting-with-the-dapp-in-a-browser

:step01: {step01-url}[Introduction]
:step02: {step02-url}[Introduction]
:step02-1: {step02-1-url}[{step02-1-title}]
:step02-2: {step02-2-url}[{step02-2-title}]
:step02-3: {step02-3-url}[{step02-3-title}]
:step03: {step03-url}[Introduction]
:step04: {step04-url}[Introduction]
:step05: {step05-url}[Introduction]
:step06: {step06-url}[Introduction]

This is a way to execute the https://www.trufflesuite.com/tutorials/pet-shop["Ethereum Pet Shop -- Your First Dapp"] (https://github.com/trufflesuite/trufflesuite.com/blob/master/src/tutorials/pet-shop.md[source page] last updated in https://github.com/trufflesuite/trufflesuite.com/commit/31156e38dd4748f20707aeb6be50f5496c53accd#diff-c305a60e191333844943b8800949a9ee[this commit]). You can follow the steps below only by copying and paste the commands (from here to your Bash shell). When you finish running the steps presented here, you will get a local git repository called `ethereum-pet-shop` (https://github.com/paulojeronimo/ethereum-pet-shop[like this]).

[NOTE]
====
. To continue you will need a Bash shell environment (of course) with Git installed.
. I only tested this steps on macOS and Linux. Maybe it can be run in Windows (through {Cygwin} for example).
====

[[step00]]
== {step00-title}

Before start, install `node` and `npm`.

[TIP]
.Installation on Arch Linux
====
----
$ sudo pacman -S node npm
----
====

[NOTE]
.Last environment tested (on macOS)
====
----
$ node -v
v12.8.0
$ npm -v
6.10.3
----
====

Load the link:functions[] in your current shell:

----
$ source ./functions
----

NOTE: This file contains some useful functions (`pet-shop*`) that I have created to minimize the number of commands that we need to type in this tutorial.

Install `truffle`:

----
$ npm i -g truffle
----

WARNING: On Arch Linux run the command above with `sudo`.

[NOTE]
.Last environment tested (on macOS)
====
----
$ truffle version
Truffle v5.0.31 (core: 5.0.31)
Solidity v0.5.0 (solc-js)
Node v12.8.0
Web3.js v1.2.1
----
====

=== References

* https://www.trufflesuite.com/tutorials/pet-shop#setting-up-the-development-environment[{step00-title}^]

[[step01]]
== {step01-title}

----
$ mkdir ethereum-pet-shop && cd $_
$ truffle unbox pet-shop
----

----
$ vim
# Explore directory structure and files
# <Ctrl-Z>
----

----
$ pet-shop init
# <Ctrl-Z>
# Open README.adoc (generated)
# <Ctrl-Z>
----

----
$ git log --name-status
----

=== References

* https://www.trufflesuite.com/tutorials/pet-shop#creating-a-truffle-project-using-a-truffle-box[{step01-title}]

[[step02]]
== {step02-title}

{step02}

----
$ pet-shop add contracts/Adoption.sol <<'EOF'
pragma solidity ^0.5.0;

contract Adoption {

}
EOF
$ git log --name-status
----

{step02-1}

[subs="attributes+"]
----
$ pet-shop apply ../patches/01.patch '{step02-1-title}'
$ git log --name-status
----

{step02-2}

[subs="attributes+"]
----
$ pet-shop apply ../patches/02.patch '{step02-2-title}'
----

{step02-3}

[subs="attributes+"]
----
$ pet-shop apply ../patches/03.patch '{step02-3-title}'
----

[[step03]]
== {step03-title}

{step03}

----
$ truffle compile
# some warnings will appear ... normal!
----

----
$ pet-shop add migrations/2_deploy_contracts.js <<'EOF'
var Adoption = artifacts.require("Adoption");

module.exports = function(deployer) {
  deployer.deploy(Adoption);
};
EOF
----

Download and install https://www.trufflesuite.com/ganache[Ganache]. Double click the icon to launch the application.

[TIP]
.Installation/ execution on Arch Linux
====
----
$ yaourt ganache
$ ganache &> /dev/null &
----
====

----
$ truffle migrate
$ tree build/
----

----
$ echo build >> .gitignore
$ git commit -am 'File .gitignore modified'
----

[[step04]]
== {step04-title}

{step04}

----
$ pet-shop add test/TestAdoption.sol <<'EOF'
pragma solidity ^0.5.0;

import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
import "../contracts/Adoption.sol";

contract TestAdoption {
 // The address of the adoption contract to be tested
 Adoption adoption = Adoption(DeployedAddresses.Adoption());

 // The id of the pet that will be used for testing
 uint expectedPetId = 8;

 //The expected owner of adopted pet is this contract
 address expectedAdopter = address(this);

}
EOF
----

https://www.trufflesuite.com/tutorials/pet-shop#testing-the-adopt-function[Testing the adopt() function]

----
$ pet-shop apply ../patches/04.patch 'Testing the adopt() function'
----

https://www.trufflesuite.com/tutorials/pet-shop#testing-retrieval-of-a-single-pet-39-s-owner[Testing retrieval of a single pet's owner]

----
$ pet-shop apply ../patches/05.patch "Testing retrieval of a single pet's owner"
----

https://www.trufflesuite.com/tutorials/pet-shop#testing-retrieval-of-all-pet-owners[Testing retrieval of all pet owners]

----
$ pet-shop apply ../patches/06.patch "Testing retrieval of all pet owners"
----

https://www.trufflesuite.com/tutorials/pet-shop#running-the-tests[Running the tests]

----
$ truffle test
----

[[step05]]
== {step05-title}

{step05}

https://www.trufflesuite.com/tutorials/pet-shop#instantiating-web3[Instantiating web3]

----
$ pet-shop apply ../patches/07.patch 'Instantiating web3'
----

https://www.trufflesuite.com/tutorials/pet-shop#instantiating-the-contract[Instantiating the contract]

----
$ pet-shop apply ../patches/08.patch 'Instantiating the contract'
----

https://www.trufflesuite.com/tutorials/pet-shop#getting-the-adopted-pets-and-updating-the-ui[Getting The Adopted Pets and Updating The UI]

----
$ pet-shop apply ../patches/09.patch 'Getting The Adopted Pets and Updating The UI'
----

https://www.trufflesuite.com/tutorials/pet-shop#handling-the-adopt-function[Handling the adopt() Function]

----
$ pet-shop apply ../patches/10.patch 'Handling the adopt() Function'
----

[[step06]]
== {step06-title}

{step06}

https://www.trufflesuite.com/tutorials/pet-shop#installing-and-configuring-metamask[Installing and configuring MetaMask]

https://www.trufflesuite.com/tutorials/pet-shop#installing-and-configuring-lite-server[Installing and configuring lite-server]

----
$ cat bs-config.json
$ sed -n '9,12p' package.json
----

https://www.trufflesuite.com/tutorials/pet-shop#using-the-dapp[Using the dapp]

----
$ npm run dev
----

Congratulations! You have taken a huge step to becoming a full-fledged dapp developer.
