= Ethereum/ Truffle Pet Shop Tutorial
Paulo Jerônimo <paulojeronimo@gmail.com>; {localdate}
:experimental:
:icons: font
:idprefix:
:idseparator: -
:nofooter:
:toc: left

// URIs
:uri-step03: https://www.trufflesuite.com/tutorial/#compiling-and-migrating-the-smart-contract
:uri-step04: https://www.trufflesuite.com/tutorial/#testing-the-smart-contract-using-solidity
:uri-step05: https://www.trufflesuite.com/tutorial/#creating-a-user-interface-to-interact-with-the-smart-contract
:uri-step06: https://www.trufflesuite.com/tutorial/#interacting-with-the-dapp-in-a-browser
:uri-step02: https://www.trufflesuite.com/tutorial/#writing-the-smart-contract
:uri-step02-1: https://www.trufflesuite.com/tutorial/#variable-setup
:uri-step02-2: https://www.trufflesuite.com/tutorial/#your-first-function-adopting-a-pet
:uri-step02-3: https://www.trufflesuite.com/tutorial/#your-second-function-retrieving-the-adopters
:uri-nvm: https://github.com/nvm-sh/nvm
:uri-tutorial: https://www.trufflesuite.com/tutorial
:uri-tutorial-index-md: https://github.com/trufflesuite/trufflesuite.com/blob/84c0d7737219879d3f2f8e4ca89246763e693d0e/src/tutorial/index.md
:uri-last-commit: https://github.com/trufflesuite/trufflesuite.com/commit/84c0d7737219879d3f2f8e4ca89246763e693d0e
:uri-paulojeronimo-ethereum-pet-shop-ftecm221: https://github.com/paulojeronimo/ethereum-pet-shop-ftecm221

// Attributes
:step02-1-title: Variable setup
:step02-2-title: Your first function: Adopting a pet
:step02-3-title: Your second function: Retrieving the adopters
:step02-1: {uri-step02-1}[{step02-1-title}]
:step02-2: {uri-step02-2}[{step02-2-title}]
:step02-3: {uri-step02-3}[{step02-3-title}]
:nvm: {uri-nvm}[nvm]

== Introduction

This is a way to execute the {uri-tutorial}["Pet Shop Tutorial"]
({uri-tutorial-index-md}[source page] last updated in
{uri-last-commit}[this commit]).
You can follow the steps below only by copying and paste the commands
(from here to your Bash shell).
When you finish running the steps presented here, you will get a local
git repository called `ethereum-pet-shop-ftecm221`
({uri-paulojeronimo-ethereum-pet-shop-ftecm221}[like this]).

[NOTE]
====
. To continue you will need a Bash shell environment (of course) with
  Git installed.
. I only tested this steps on Ubuntu (running it through WSL2).
====

[[step00]]
== Setting up the development environment

https://www.trufflesuite.com/tutorial#setting-up-the-development-environment[Introduction]

Before start, install `node` and `npm`.

[TIP]
.Installation on Ubuntu
====
. Install {nvm}.
. Install node through {nvm}:
----
$ nvm install --lts
----
====

[NOTE]
.Last environment tested
====
----
$ nvm -v
0.39.1
$ node -v
v16.14.2
$ npm -v
8.5.0
----
====

Clone this project and change your current directory to it:

----
$ repo=https://github.com/paulojeronimo/ethereum-pet-shop-tutorial
$ git clone $repo && cd $(basename "$repo")
$ git checkout ftecm221
----

Load the link:functions.sh[] in your current shell:

----
$ source ./functions.sh
----

NOTE: This file contains some useful functions (like `pet-shop` and
`gc`) that I have created to minimize the number of commands that we
need to type in this tutorial.

Install `truffle`:

----
$ npm i -g truffle
----

[NOTE]
.Last environment tested
====
----
$ truffle version
Truffle v5.5.10 (core: 5.5.10)
Ganache v^7.0.3
Solidity v0.5.16 (solc-js)
Node v16.14.2
Web3.js v1.5.3
----
====

[[step01]]
== Creating a Truffle project using a Truffle Box

https://www.trufflesuite.com/tutorial#creating-a-truffle-project-using-a-truffle-box[Introduction]

----
$ mkdir ethereum-pet-shop-ftecm221 && cd $_
$ truffle unbox pet-shop
----

----
$ pet-shop init
----

Read the generated README.adoc.

----
$ git log --name-status
----

[[step02]]
== Writing the smart contract

{uri-step02}[Introduction]

----
$ pet-shop add contracts/Adoption.sol <<'EOF'
pragma solidity ^0.5.0;

contract Adoption {

}
EOF
$ git log --name-status
----

{step02-1}

[subs="attributes+"]
----
$ pet-shop apply ../patches/01.patch '{step02-1-title}'
$ git log --name-status
----

{step02-2}

[subs="attributes+"]
----
$ pet-shop apply ../patches/02.patch '{step02-2-title}'
----

{step02-3}

[subs="attributes+"]
----
$ pet-shop apply ../patches/03.patch '{step02-3-title}'
----

[[step03]]
== Compiling and migrating the smart contract

{uri-step03}[Introduction]

----
$ truffle compile
# some warnings will appear ... normal!
----

----
$ pet-shop add migrations/2_deploy_contracts.js <<'EOF'
var Adoption = artifacts.require("Adoption");

module.exports = function(deployer) {
  deployer.deploy(Adoption);
};
EOF
----

Install `ganache`:

----
$ npm install -g ganache
----

Start `ganache`:

----
$ gc start
----

[NOTE]
====
The `gc` command is also a function loaded by the link:function[]
script.
Its source code is in the file link:ganache.sh[].
You can see the code for this function executing:

----
$ type gc
----

If you want to follow the log produced by `ganache` type the following
command:

----
$ gc log tail
$ # Press <kbd:Ctrl+C> to stop seeing the log. This will not kill
ganache
----
====

----
$ truffle migrate
$ tree build/
----

----
$ echo build >> .gitignore
$ git commit -am 'File .gitignore modified'
----

[[step04]]
== Testing the smart contract using Solidity

{uri-step04}[Introduction]

----
$ pet-shop add test/TestAdoption.sol <<'EOF'
pragma solidity ^0.5.0;

import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
import "../contracts/Adoption.sol";

contract TestAdoption {
 // The address of the adoption contract to be tested
 Adoption adoption = Adoption(DeployedAddresses.Adoption());

 // The id of the pet that will be used for testing
 uint expectedPetId = 8;

 //The expected owner of adopted pet is this contract
 address expectedAdopter = address(this);

}
EOF
----

https://www.trufflesuite.com/tutorial#testing-the-adopt-function[Testing the adopt() function]

----
$ pet-shop apply ../patches/04.patch 'Testing the adopt() function'
----

https://trufflesuite.com/tutorial/#testing-retrieval-of-a-single-pets-owner[Testing retrieval of a single pet's owner]

----
$ pet-shop apply ../patches/05.patch "Testing retrieval of a single pet's owner"
----

https://www.trufflesuite.com/tutorial#testing-retrieval-of-all-pet-owners[Testing retrieval of all pet owners]

----
$ pet-shop apply ../patches/06.patch "Testing retrieval of all pet owners"
----

https://www.trufflesuite.com/tutorial#running-the-tests[Running the tests]

----
$ truffle test
----

[[step05]]
== Creating a user interface to interact with the smart contract

{uri-step05}[Introduction]

https://www.trufflesuite.com/tutorial#instantiating-web3[Instantiating web3]

----
$ pet-shop apply ../patches/07.patch 'Instantiating web3'
----

https://www.trufflesuite.com/tutorial#instantiating-the-contract[Instantiating the contract]

----
$ pet-shop apply ../patches/08.patch 'Instantiating the contract'
----

https://www.trufflesuite.com/tutorial#getting-the-adopted-pets-and-updating-the-ui[Getting The Adopted Pets and Updating The UI]

----
$ pet-shop apply ../patches/09.patch 'Getting The Adopted Pets and Updating The UI'
----

https://www.trufflesuite.com/tutorial#handling-the-adopt-function[Handling the adopt() Function]

----
$ pet-shop apply ../patches/10.patch 'Handling the adopt() Function'
----

[[step06]]
== Interacting with the dapp in a browser

{uri-step06}[Introduction]

https://www.trufflesuite.com/tutorial#installing-and-configuring-metamask[Installing and configuring MetaMask]

[WARNING]
====
When configuring Metamask, use the seed phrase returned by the following
command:

----
$ gc seedphrase
----
====

https://www.trufflesuite.com/tutorial#installing-and-configuring-lite-server[Installing and configuring lite-server]

----
$ cat bs-config.json
$ sed -n '9,12p' package.json
----

https://www.trufflesuite.com/tutorial#using-the-dapp[Using the dapp]

----
$ npm run dev
----

Open your browser in http://localhost:3000 and test the app.

Congratulations!
You have taken a huge step to becoming a full-fledged dapp developer.
